### PR TITLE
Refactor using xpublish custom routers

### LINKED ISSUE #6: Return model grid coordinate values along with extracted model data
From my https://github.com/ESM-VFC/esm-vfc-api-demo/pull/2#discussion_r431665874 :

> Since the coordinates are already provided in the query data (as GEOJson), I'm not sure if we actually need to return it.

Actually, we should return it. For nearest-neighbor lookup: model grid coordinate values != observation points coordinate values. Model coordinate values may be useful on the client side.

### PR DESCRIPTION
**Pull request by benbovy**
This simplifies things:

- We don't need two applications anymore. Only one application is running in one Docker container (see the updated README).
- There is now auto-generated, interactive API documentation (swagger) available at the `/docs` API endpoint. @alirezamdv I think it will be much easier for you to use this rather than going through the previous examples shown in a jupyter notebook.

Also closes #6. The `/esm/extract_tracks` endpoint now returns GeoJSON formatted data, just like input data (field values are returned as feature properties).

TODO:

- ~~Support `MultiLineString` features.~~ Will be done in a follow-up PR.

### CODE REVIEW

**Review by willirath — COMMENTED** [review]
In http://127.0.0.1:8000/docs#/esm/extract_tracks_esm_extract_tracks_post, I can't run the example which is
```python
{
  "transform": {
    "aggregation": "mean",
    "dim": "time"
  },
  "tracks": {
    "type": "FeatureCollection",
    "features": [
      {
        "type": "Feature",
        "geometry": {
          "type": "LineString",
          "coordinates": [
            [
              71.591269,
              27.809646
            ],
            [
              74.112343,
              34.536865
            ],
            [
              77.23488,
              60.95901
            ],
            [
              81.7773,
              80.55286
            ]
          ]
        },
        "id": "track-1"
      }
    ]
  }
}
```
because it lacks the `fieldnames`.

**Comment by benbovy** [comment]
Yeah that's a bit unfortunate, but on the other hand it would be a bit overkill to create a pydantic model (with an example) just for the fieldnames parameter.

Maybe we could make it optional (by default return extracted values for all data variables in dataset)?

**Comment by benbovy** [comment]
The example should work now without any modification.

**Comment by willirath** [comment]
Looks great now!

**Comment by benbovy** [comment]
We could do a better job at handling errors (for example, a bad fieldname will return a `internal server error`), but this could be done later.

I'm going to merge this.

**Comment by benbovy** [comment]
Actually, I don't have commit rights on this repo so I can't merge it :)

**Comment by willirath** [comment]
@benbovy I've given you maintainer status here. Lets see if this helps.

**Comment by benbovy** [comment]
Great, thanks!

**Pull request merged**
