### PR TITLE
Simple flask app follow-up

### PR DESCRIPTION
**Pull request by benbovy**
Follow-up from #2. 

Extract tracks query:

- Fix json response (was not properly formatted)
- Allow providing multiple field names (this might save computation in the backend and some request/response round-trips as well).

### CODE REVIEW

**Comment by benbovy** [comment]
This is ready ;-)

**Comment by willirath** [comment]
> This is ready ;-)

Looks good.

One thing: With
```python
requests.get(server_url + '/api/v1.0/datasets/demo/fieldnames').json()
```
lists all keys (including coords) as fieldnames, because <https://github.com/ESM-VFC/esm-vfc-api-demo/blob/1355452d3f60fd5427349b9dbc786282cec7baac/app/app.py#L35> uses the Zarr keys for variable name lookup. I'd change to
```python
fieldnames = list(xr.open_zarr(demo_dataset_http_map, consolidated=True).data_vars.keys())
```

**Comment by benbovy** [comment]
Agreed, it's better to return data variables only. 

I made the change but I think it will be better to fix this upstream, as `xr.open_zarr()` is pretty heavy (i.e., all metadata is passed) just for getting the names of the data variables.

I'll open a couple of issues in the xpublish repo.

**Comment by willirath** [comment]
> I'll open a couple of issues in the xpublish repo.

👍

**Pull request merged**
